// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeStream.VisualStudio.Vsix.x64
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeStreamPackageString = "5498f07e-2ca1-4d3b-bcfb-5e8a8a082eed";
        public static Guid guidCodeStreamPackage = new Guid(guidCodeStreamPackageString);

        public const string guidVSPackageCommandTopMenuCmdSetString = "acf32b59-19bf-4492-b19b-2d359e74a69a";
        public static Guid guidVSPackageCommandTopMenuCmdSet = new Guid(guidVSPackageCommandTopMenuCmdSetString);

        public const string NewRelicLogoGuidString = "70d5e386-b774-4566-96a7-233c0cb02142";
        public static Guid NewRelicLogoGuid = new Guid(NewRelicLogoGuidString);

        public const string guidImagesString = "f2c8ef6d-3257-4e0a-8ae0-ef6298dd22c5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeStreamTopLevelMenu = 0x1020;
        public const int CodeStreamTopLevelMenuCommandGroup = 0x1021;
        public const int CodeStreamTopLevelMenuToggleCommand = 0x0101;
        public const int CodeStreamTopLevelMenuSignOutCommand = 0x0102;
        public const int CodeStreamTopLevelMenuReloadCommand = 0x0103;
        public const int logo = 0x0001;
        public const int empty1 = 0x0001;
        public const int auth = 0x0002;
        public const int user = 0x0003;
        public const int empty4 = 0x0004;
        public const int empty5 = 0x0005;
        public const int empty6 = 0x0006;
    }
}